// GENERATED by tools/process-images.mjs - do not edit by hand.
// Source: reference/squarespace/content/projects.json

export interface Project {
  /** Filename stem under public/img/projects/, e.g. `<slug>-800.webp`. */
  readonly slug: string;
  /** Municipality or descriptor, as shown under the tile. */
  readonly location: string;
  /** Transaction status: Sold, Co-sales, Share deal, Rented, ... */
  readonly status: string;
  /** Widths actually emitted, smallest first. */
  readonly widths: readonly number[];
  readonly width: number;
  readonly height: number;
  /** Included in the homepage slideshow subset. */
  readonly onHome: boolean;
}

export const PROJECTS: readonly Project[] = [
  {
    "slug": "sint-martens-latem-sold",
    "location": "Sint-Martens-Latem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1669,
    "onHome": true
  },
  {
    "slug": "sold-wetteren",
    "location": "Wetteren",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": true
  },
  {
    "slug": "sold-merelbeke",
    "location": "Merelbeke",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": true
  },
  {
    "slug": "discrete-sale-share-deal",
    "location": "Discrete Sale - Share deal",
    "status": "",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": true
  },
  {
    "slug": "oostende-sold",
    "location": "Oostende",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": false
  },
  {
    "slug": "honegem-sold",
    "location": "Honegem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1536,
    "onHome": false
  },
  {
    "slug": "brugge-sold",
    "location": "Brugge",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "nevele-sold",
    "location": "Nevele",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "sint-denijs-westrem-co-sales",
    "location": "Sint-Denijs-Westrem",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": false
  },
  {
    "slug": "ledegem-sold",
    "location": "Ledegem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "edingen-sold-regional-record-sale",
    "location": "Edingen",
    "status": "Sold - Regional Record Sale *****",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "brugge-sales-support-project",
    "location": "Brugge",
    "status": "Sales support project",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "heusden-share-deal",
    "location": "Heusden",
    "status": "Share deal",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1669,
    "onHome": true
  },
  {
    "slug": "laarne-sold",
    "location": "Laarne",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1669,
    "onHome": true
  },
  {
    "slug": "de-pinte-co-sales",
    "location": "De Pinte",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1406,
    "onHome": true
  },
  {
    "slug": "sint-martens-latem-sold-regional-record-sale",
    "location": "Sint-Martens-Latem",
    "status": "Sold - Regional Record Sale *****",
    "widths": [
      480,
      800
    ],
    "width": 1063,
    "height": 709,
    "onHome": true
  },
  {
    "slug": "knokke-share-deal",
    "location": "Knokke",
    "status": "Share deal",
    "widths": [
      480,
      800
    ],
    "width": 1024,
    "height": 683,
    "onHome": true
  },
  {
    "slug": "brussel-share-deal-support-advice",
    "location": "Brussel",
    "status": "Share deal support & advice",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1486,
    "onHome": true
  },
  {
    "slug": "lo-reninge-sold",
    "location": "Lo-Reninge",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "waregem-sold",
    "location": "Waregem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1875,
    "onHome": true
  },
  {
    "slug": "gent-expat-rented",
    "location": "Gent",
    "status": "Expat rented",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1856,
    "onHome": true
  },
  {
    "slug": "sint-martens-latem-sold-22",
    "location": "Sint-Martens-Latem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1536,
    "onHome": true
  },
  {
    "slug": "gent-sold",
    "location": "Gent",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1663,
    "onHome": true
  },
  {
    "slug": "deurle-short-term-rented",
    "location": "Deurle",
    "status": "Short term rented",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "lembeke-sold",
    "location": "Lembeke",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1875,
    "onHome": true
  },
  {
    "slug": "deurle-sold",
    "location": "Deurle",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1406,
    "onHome": true
  },
  {
    "slug": "sint-martens-latem-sold-2x",
    "location": "Sint-Martens-Latem",
    "status": "Sold (2x)",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1363,
    "onHome": true
  },
  {
    "slug": "oosteeklo-sold",
    "location": "Oosteeklo",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "zele-block-sale-22-appartementen",
    "location": "Zele",
    "status": "Block sale - 22 appartementen",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1479,
    "onHome": true
  },
  {
    "slug": "jette-sold",
    "location": "Jette",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": false
  },
  {
    "slug": "watou-sold-2x",
    "location": "Watou",
    "status": "Sold (2x)",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "oudenburg-sold",
    "location": "Oudenburg",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1875,
    "onHome": true
  },
  {
    "slug": "tervuren-co-sales",
    "location": "Tervuren",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "deurle-confidential-file",
    "location": "Deurle",
    "status": "Confidential file",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "deurle-renovation-project",
    "location": "Deurle",
    "status": "Renovation project",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "knokke-verkaveling-regional-record-sale",
    "location": "Knokke",
    "status": "Verkaveling - Regional Record Sale *****",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1804,
    "onHome": true
  },
  {
    "slug": "vlezenbeek-co-sales",
    "location": "Vlezenbeek",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1049,
    "onHome": true
  },
  {
    "slug": "gent-high-end-project-onefifty-kouter",
    "location": "Gent",
    "status": "High-end project - OneFifty Kouter",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1663,
    "onHome": true
  },
  {
    "slug": "sint-martens-latem-sold-39",
    "location": "Sint-Martens-Latem",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1667,
    "onHome": true
  },
  {
    "slug": "gent-sold-40",
    "location": "Gent",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1663,
    "onHome": true
  },
  {
    "slug": "brugge-co-sales",
    "location": "Brugge",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 2008,
    "onHome": true
  },
  {
    "slug": "deurle-sold-42",
    "location": "Deurle",
    "status": "Sold",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1875,
    "onHome": true
  },
  {
    "slug": "lochristi-co-sales",
    "location": "Lochristi",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1666,
    "onHome": true
  },
  {
    "slug": "temse-co-sales",
    "location": "Temse",
    "status": "Co-sales",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2000,
    "height": 1333,
    "onHome": true
  },
  {
    "slug": "waregem-bedrijvencomplex",
    "location": "Waregem",
    "status": "Bedrijvencomplex",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2048,
    "height": 1046,
    "onHome": true
  },
  {
    "slug": "aalst-share-deal",
    "location": "Aalst",
    "status": "Share deal",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2016,
    "height": 1512,
    "onHome": true
  },
  {
    "slug": "gent-real-estate-holding-company",
    "location": "Gent",
    "status": "Real estate holding company",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 2500,
    "height": 1406,
    "onHome": true
  }
] as const;

export const HOME_PROJECTS: readonly Project[] = PROJECTS.filter((p) => p.onHome);
